USE iotdb;

DROP TABLE IF EXISTS T07_CLUSTERTHINGS;
DROP TABLE IF EXISTS T06_CLUSTERS;
DROP TABLE IF EXISTS T05_THINGS;
DROP TABLE IF EXISTS T04_THINGTYPES;
DROP TABLE IF EXISTS T03_PLANTS;
DROP TABLE IF EXISTS T02_DATA;
DROP TABLE IF EXISTS T01_VARIABLES;


CREATE TABLE T01_VARIABLES (
	T01_ID int NOT NULL AUTO_INCREMENT,
	T01_KEY int UNIQUE NOT NULL,
	T01_NAME varchar(255) NOT NULL,
	T01_OBS varchar(1024),
	PRIMARY KEY(T01_ID));

CREATE TABLE T02_DATA (
	T02_ID int NOT NULL AUTO_INCREMENT,
	T02_T01_VARIABLE int,
	T02_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	T02_DATA int,
	PRIMARY KEY(T02_ID),
	FOREIGN KEY(T02_T01_VARIABLE) REFERENCES T01_VARIABLES(T01_ID));
	

CREATE TABLE T03_PLANTS (
	T03_ID int NOT NULL AUTO_INCREMENT,
	T03_NAME varchar(32) NOT NULL UNIQUE,
	T03_IMAGE varchar(64) NOT NULL,
	T03_SCALEX float NOT NULL DEFAULT 1.0,
	T03_SCALEY float NOT NULL DEFAULT 1.0,
	PRIMARY KEY(T03_ID)
);	
	
CREATE TABLE T04_THINGTYPES (
	T04_ID int NOT NULL AUTO_INCREMENT,
	T04_NAME varchar(16) NOT NULL UNIQUE,
	T04_STATES int NOT NULL DEFAULT 2,
	PRIMARY KEY(T04_ID)
);	
	
CREATE TABLE T05_THINGS (
	T05_ID int NOT NULL AUTO_INCREMENT,
	T05_NAME varchar(128),
	T05_T04_TYPE int NOT NULL,
	T05_T03_PLANT int NOT NULL,
	T05_X int NOT NULL,  -- X Position in Plant
	T05_Y int NOT NULL, -- Y Position inn Plant
	T05_STATE int NOT NULL DEFAULT 0,
	PRIMARY KEY(T05_ID),
	FOREIGN KEY(T05_T04_TYPE) REFERENCES T04_THINGTYPES(T04_ID),
	FOREIGN KEY(T05_T03_PLANT) REFERENCES T03_PLANTS(T03_ID)
);

CREATE TABLE T06_CLUSTERS (
	T06_ID int NOT NULL AUTO_INCREMENT,
	T06_NAME varchar(128),
	PRIMARY KEY(T05_ID)
);
	
CREATE TABLE T07_CLUSTERTHINGS (
	T07_CLUSTERID int NOT NULL,
	T07_THINGID int NOT NULL,
	FOREIGN KEY(T07_CLUSTERID) REFERENCES T06_CLUSTERS(T06_ID),
	FOREIGN KEY(T07_THINGID) REFERENCES T05_THINGS(T05_ID)
);	


	