DROP TABLE IF EXISTS T02_DATA;
DROP TABLE IF EXISTS T01_VARIABLES;


CREATE TABLE T01_VARIABLES (
	T01_ID int NOT NULL AUTO_INCREMENT,
	T01_KEY int UNIQUE NOT NULL,
	T01_NAME varchar(255) NOT NULL,
	T01_OBS varchar(1024),
	PRIMARY KEY(T01_ID));

CREATE TABLE T02_DATA (
	T02_ID int NOT NULL AUTO_INCREMENT,
	T02_T01_VARIABLE int,
	T02_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	T02_DATA int,
	PRIMARY KEY(T02_ID),
	FOREIGN KEY(T02_T01_VARIABLE) REFERENCES T01_VARIABLES(T01_ID));
	